// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudfoundry/uaa-lite/internal/auth (interfaces: JWTManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_jwt_manager.go -package=mocks . JWTManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	auth "github.com/cloudfoundry/uaa-lite/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTManager is a mock of JWTManager interface.
type MockJWTManager struct {
	ctrl     *gomock.Controller
	recorder *MockJWTManagerMockRecorder
	isgomock struct{}
}

// MockJWTManagerMockRecorder is the mock recorder for MockJWTManager.
type MockJWTManagerMockRecorder struct {
	mock *MockJWTManager
}

// NewMockJWTManager creates a new mock instance.
func NewMockJWTManager(ctrl *gomock.Controller) *MockJWTManager {
	mock := &MockJWTManager{ctrl: ctrl}
	mock.recorder = &MockJWTManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTManager) EXPECT() *MockJWTManagerMockRecorder {
	return m.recorder
}

// CreateAccessToken mocks base method.
func (m *MockJWTManager) CreateAccessToken(userID, username, clientID string, scopes []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", userID, username, clientID, scopes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessToken indicates an expected call of CreateAccessToken.
func (mr *MockJWTManagerMockRecorder) CreateAccessToken(userID, username, clientID, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockJWTManager)(nil).CreateAccessToken), userID, username, clientID, scopes)
}

// CreateAccessTokenWithOptions mocks base method.
func (m *MockJWTManager) CreateAccessTokenWithOptions(userID, username, clientID string, scopes []string, opts auth.TokenOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessTokenWithOptions", userID, username, clientID, scopes, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessTokenWithOptions indicates an expected call of CreateAccessTokenWithOptions.
func (mr *MockJWTManagerMockRecorder) CreateAccessTokenWithOptions(userID, username, clientID, scopes, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessTokenWithOptions", reflect.TypeOf((*MockJWTManager)(nil).CreateAccessTokenWithOptions), userID, username, clientID, scopes, opts)
}

// CreateRefreshToken mocks base method.
func (m *MockJWTManager) CreateRefreshToken(userID, username, clientID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", userID, username, clientID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockJWTManagerMockRecorder) CreateRefreshToken(userID, username, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockJWTManager)(nil).CreateRefreshToken), userID, username, clientID)
}

// GetPublicKey mocks base method.
func (m *MockJWTManager) GetPublicKey(keyID string) (*rsa.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey", keyID)
	ret0, _ := ret[0].(*rsa.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockJWTManagerMockRecorder) GetPublicKey(keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockJWTManager)(nil).GetPublicKey), keyID)
}

// GetPublicKeys mocks base method.
func (m *MockJWTManager) GetPublicKeys() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKeys")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKeys indicates an expected call of GetPublicKeys.
func (mr *MockJWTManagerMockRecorder) GetPublicKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKeys", reflect.TypeOf((*MockJWTManager)(nil).GetPublicKeys))
}

// ValidateToken mocks base method.
func (m *MockJWTManager) ValidateToken(tokenString string) (*auth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(*auth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockJWTManagerMockRecorder) ValidateToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockJWTManager)(nil).ValidateToken), tokenString)
}
