// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudfoundry/uaa-lite/internal/auth (interfaces: GrantHandler)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_grant_handler.go -package=mocks . GrantHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	auth "github.com/cloudfoundry/uaa-lite/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockGrantHandler is a mock of GrantHandler interface.
type MockGrantHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGrantHandlerMockRecorder
	isgomock struct{}
}

// MockGrantHandlerMockRecorder is the mock recorder for MockGrantHandler.
type MockGrantHandlerMockRecorder struct {
	mock *MockGrantHandler
}

// NewMockGrantHandler creates a new mock instance.
func NewMockGrantHandler(ctrl *gomock.Controller) *MockGrantHandler {
	mock := &MockGrantHandler{ctrl: ctrl}
	mock.recorder = &MockGrantHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrantHandler) EXPECT() *MockGrantHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockGrantHandler) Handle(req *auth.TokenRequest) (*auth.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", req)
	ret0, _ := ret[0].(*auth.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockGrantHandlerMockRecorder) Handle(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockGrantHandler)(nil).Handle), req)
}
