// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudfoundry/uaa-lite/internal/auth (interfaces: RefreshTokenStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_refresh_store.go -package=mocks . RefreshTokenStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	auth "github.com/cloudfoundry/uaa-lite/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenStore is a mock of RefreshTokenStore interface.
type MockRefreshTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenStoreMockRecorder
	isgomock struct{}
}

// MockRefreshTokenStoreMockRecorder is the mock recorder for MockRefreshTokenStore.
type MockRefreshTokenStoreMockRecorder struct {
	mock *MockRefreshTokenStore
}

// NewMockRefreshTokenStore creates a new mock instance.
func NewMockRefreshTokenStore(ctrl *gomock.Controller) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStoreMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRefreshTokenStore) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockRefreshTokenStoreMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRefreshTokenStore)(nil).Count))
}

// Retrieve mocks base method.
func (m *MockRefreshTokenStore) Retrieve(token string) (*auth.RefreshTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", token)
	ret0, _ := ret[0].(*auth.RefreshTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockRefreshTokenStoreMockRecorder) Retrieve(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockRefreshTokenStore)(nil).Retrieve), token)
}

// StartCleanup mocks base method.
func (m *MockRefreshTokenStore) StartCleanup(ctx context.Context, interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartCleanup", ctx, interval)
}

// StartCleanup indicates an expected call of StartCleanup.
func (mr *MockRefreshTokenStoreMockRecorder) StartCleanup(ctx, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCleanup", reflect.TypeOf((*MockRefreshTokenStore)(nil).StartCleanup), ctx, interval)
}

// Store mocks base method.
func (m *MockRefreshTokenStore) Store(data auth.RefreshTokenData) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", data)
	ret0, _ := ret[0].(string)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockRefreshTokenStoreMockRecorder) Store(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRefreshTokenStore)(nil).Store), data)
}
